### ISSUE TITLE
"No such file or directory" error

### ISSUE THREAD

**Issue by juanghurtado** [brianleroux/Cordova#15]
Hi there,

I'm trying to install Cordova, but after doing the `python setup.py install` (without errors), having my `phonegap` command available and Cordova path added to my $PATH, I get the following error while trying to `phonegap create sample_app`:

```
Traceback (most recent call last):
  File "/usr/local/share/python/phonegap", line 9, in <module>
    load_entry_point('cordova==0.1.0', 'console_scripts', 'phonegap')()
  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/cordova-0.1.0-py2.7.egg/cordova/console.py", line 33, in main
    console.run()
  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/cordova-0.1.0-py2.7.egg/cordova/console.py", line 25, in run
    command[0](self).run()
  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/cordova-0.1.0-py2.7.egg/cordova/commands/create.py", line 51, in run
    shutil.copytree(tmpl, dest)
  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/shutil.py", line 168, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: '/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/cordova-0.1.0-py2.7.egg/generate-template' 
```

Any ideas? Thanks a lot.

PS.- I have tried with both, native OSX and Homebrew, python. My OSX version is Lion.

**Comment by avinasha** [comment]
I have the same error...

**Comment by brandon-rhodes** [comment]
And I have the same error as well.

**Comment by brandon-rhodes** [comment]
This looks like the same issue as Issue #7 because both "generate-template" and "recipes" are directories sitting next to the "cordova" package, but that fail to get installed alongside it during "setup.py install".  I will make further comments on that other issue:

https://github.com/brianleroux/Cordova/issues/7

**Comment by samyakbhuta** [comment]
Manual copying does solve the issue. Watch out your python version, though, before you fire the below command from your `cordova` direcotry.

```
sudo cp -R ../Cordova/recipes /Library/Python/2.7/site-packages/cordova-0.1.0-py2.7.egg/
```

```
sudo cp -R ../Cordova/generate-template /Library/Python/2.7/site-packages/cordova-0.1.0-py2.7.egg/
```
